### ISSUE TITLE
hkaSplineSkeletalAnimation

### ISSUE THREAD

**Issue by Nostritius** [PredatorCZ/HavokLib#2]
Hi,
I'm currently writing a pure python blender plugin based on your HavokLib code, to research some havok files from a specific game (Alan Wake). HavokLib proved to be great source of information and verification for that. In these files I found another type of animation, hkaSplineSkeletalAnimation. Is it equivalent to hkaSplineCompressedAnimation? If not, would you consider this as a feature request?

**Comment by PredatorCZ** [comment]
1. HavokLib already contains some python wrapping (through it need to be finished).
2. It's same class.

**Comment by Nostritius** [comment]
Thanks, that was everything I wanted to know
